Complies with shellcheck.com standars
Quotes all variables to prevent globbing, splitting and nasty bugs.

diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -10,7 +10,7 @@ CLIPBOARD=true
 
 # function to output usage instructions
 function usage {
-	echo "Usage: $(basename $0) <filename>
+	echo "Usage: $(basename "$0") <filename>
 Upload an image to imgur, print its URL to stdout, and print the delete page URL to stderr.
 If you're on a Mac or have xsel/xclip, copy the image URL to the clipboard." >&2
 }
@@ -60,9 +60,9 @@ response=$(curl \
 if [ $? -ne 0 ]; then
 	echo "Upload failed" >&2
 	exit 2
-elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
+elif [ "$(echo "$response" | grep -c "<error_msg>")" -gt 0 ]; then
 	echo "Error message from imgur:" >&2
-	echo $response | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
+	echo "$response" | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
 	exit 3
 elif [[ "$response" != *deletehash* ]]; then
 	echo "Unknown Failure: Imgur is probably down for maintenance."
@@ -70,15 +70,15 @@ elif [[ "$response" != *deletehash* ]]; then
 fi
 
 # parse the response and output our stuff
-url=$(echo $response | sed -E 's/.*"link":"([^"]+)".*/\1/' | sed "s|\\\\/|/|g")
-deleteurl=$(echo $response | sed -E 's/.*"deletehash":"([^"]+)".*/\1/' | sed "s|^|http://imgur.com/delete/|")
-echo $url
+url=$(echo "$response" | sed -E 's/.*"link":"([^"]+)".*/\1/' | sed "s|\\\\/|/|g")
+deleteurl=$(echo "$response" | sed -E 's/.*"deletehash":"([^"]+)".*/\1/' | sed "s|^|http://imgur.com/delete/|")
+echo "$url"
 echo "Delete page: $deleteurl" >&2
 
 # put the URL on the clipboard if we have xsel or xclip
 if [ $CLIPBOARD == true ]; then
-	{ which pbcopy &>/dev/null && echo -n $url | pbcopy; } \
-		|| { which xsel &>/dev/null && echo -n $url | xsel --input --clipboard; } \
-		|| { which xclip &>/dev/null && echo -n $url | xclip -selection clipboard; } \
+	{ which pbcopy &>/dev/null && echo -n "$url" | pbcopy; } \
+		|| { which xsel &>/dev/null && echo -n "$url" | xsel --input --clipboard; } \
+		|| { which xclip &>/dev/null && echo -n "$url" | xclip -selection clipboard; } \
 		|| echo "Haven't copied to the clipboard: no pbcopy, xsel, or xclip" >&2
 fi
